# Generated by Django 4.0.6 on 2022-07-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationInfo',
            new_name='Organization',
        ),
    ]
